version: '3.0'

services:
  grafana:
    container_name: 'maniarr-warp10backend-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.4.3}
    ports:
      - 3000:3000/tcp
    environment:
      # - GF_LOG_LEVEL=debug
      - GF_LOG_FILTERS=plugin.maniarr-warp10backend-datasource:debug
    volumes:
      - ./dist:/var/lib/grafana/plugins/maniarr-warp10backend-datasource
      - ./provisioning:/etc/grafana/provisioning